### ISSUE TITLE
Abreviaturas para los tipos de centro

### ISSUE THREAD

**Issue by s-nt-s** [s-nt-s/institutos-map#3]
La idea es concatenar al principio del nombre de cada centro una abreviatura que indique el tipo.
Por ejemplo `San Isidro` sería `IES San Isidro` o `Gloria Fuertes` sería `CEPA Gloria Fuertes`.

Algunas abreviaturas (como `IES` y `CEPA`) están claras, pero otras (como [`CIMELPR PRSEC`](http://gestiona.madrid.org/wpad_pub/run/j/MostrarFichaCentro.icm?cdCentro=28045414)) parecen demasiado largas o complicadas como para que realmente sean de uso común.

Como esto es para que los profesores identifiquen rápidamente el tipo de centro, lo interesante sería usar las abreviaturas que coloquialmente usen ellos.

Por ello si sabes cuales son las mejores abreviaturas para estos tipos de centro:

```
016 Centro integrado de enseñanzas artísticas elementales y profesionales de música, educación primaria y secundaria
017 Centro integrado de enseñanzas artísticas profesionales de música y educación secundaria
031 Centro de educación de personas adultas
035 Centro de educación adultos establecimientos penitenciarios
036 Aulas hospitalarias
042 Instituto de educación secundaria
047 Sección de instituto de educación secundaria
070 Colegio de educación infantil, primaria y secundaria
```

responde a este `issue` con ellas.

**Comment by Irenegs** [comment]
016 Centro integrado de enseñanzas artísticas elementales y profesionales de música, educación primaria y secundaria

No hay, Centro integrado sería la mejor opción

017 Centro integrado de enseñanzas artísticas profesionales de música y educación secundaria

No hay, Centro integrado sería la mejor opción

031 Centro de educación de personas adultas

CEPA

035 Centro de educación adultos establecimientos penitenciarios

No tiene, pero se puede poner Cárcel

036 Aulas hospitalarias

No tiene, pero se puede poner AAHH

042 Instituto de educación secundaria

IES

047 Sección de instituto de educación secundaria

Que yo sepa no tiene, pero se puede poner Sec IES

070 Colegio de educación infantil, primaria y secundaria

CEIPS
